[project]
name = "daskmsASTROKIT"
description = "Astro convenience functions for daskms "
license = "GPL-3.0-licence"
version = "0.0.1"
readme = "README.md"
authors = [{name = "Hans-Rainer Kloeckner", email = "hrkloeck@gmail.com"}]
requires-python = '>=3.12,<3.14'
dependencies = ['appdirs >=1.4.4', 'dask[array] >=2023.1.1,<2024.11.0', 'donfig >=0.8.0', 'python-casacore >=3.7.0', 'numpy >=2.0.0', 'fsspec >=2022.7.0', 'cacheout >=0.16.0','dask-ms >=0.2.23']

[project.scripts]
GET_MS_INFO = "daskms_ASTROKIT.apps.GET_MS_INFO:main"

[project.optional-dependencies]
astropy    = ['astropy >= 7.2']
scipy      = ['scipy >=1.13']
matplotlib = ['matplotlib >= 3.9.1']

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"