[project]
name = "daskmsASTROKIT"
version = "0.0.1"
authors = [
	{name = "Hans-Rainer Kloeckner", email = "hrkloeck@gmail.com"},
]
description = "Astro convenience functions for daskms "
readme      = "README.md"
requires-python = '>=3.12,<3.14'
license = { file = "LICENCE"}
dependencies = [
	     "dask-ms >=0.2.29","astropy >= 7.2","matplotlib >= 3.9.1"
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"